#!/usr/bin/env bash

USERNAME=${1:?First parameter must be username}
PASSWORD=${2:?Second parameter must be password}
VHOST=${3:?Third parameter must be vhost}

url="amqp://$USERNAME:$PASSWORD@rabbitmq:5672/$VHOST"

shift 1

NAME=perftest-$USERNAME

docker network inspect rabbitmq_net >/dev/null 2>&1 || docker network create rabbitmq_net
docker rm -f $NAME 2>/dev/null || echo "$NAME was not running"

docker run -d --rm \
  --network rabbitmq_net \
  --name $NAME \
  pivotalrabbitmq/perf-test:latest \
  --uri $url \
  $@
  